# Generated by Django 4.0.4 on 2022-04-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('product_code', models.TextField()),
                ('price', models.TextField()),
                ('category', models.TextField()),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('updated_at', models.DateField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
