# Generated by Django 4.0.4 on 2022-04-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_alter_products_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
        migrations.RemoveField(
            model_name='products',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
