# Generated by Django 4.0.4 on 2022-04-17 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0004_delete_users_remove_products_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='user_id',
            field=models.BigIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
